- name: Delete borg backup {{ target_location }}/{{ backup_name }}
  ansible.builtin.expect:
    command: borg delete {{ target_location }}/{{ backup_name }}
    responses:
      passphrase:
        - "{{ backup_encryption_key }}"
      DELETE:
        - "YES"
