- name: Disable a timer automatic backup
  ansible.builtin.systemd:
    name: automatic-backup-{{ service_name }}.timer
    state: started
    enabled: false
  become: true
  ignore_errors: true
- name: Remove systemd files
  ansible.builtin.file:
    path: "{{ systemd_script_target }}/{{ item }}"
    state: absent
  with_items:
    - automatic-backup-{{ service_name }}.sh
    - automatic-backup-{{ service_name }}.service
    - automatic-backup-{{ service_name }}.timer
  become: true
  ignore_errors: true
