---
- name: initialize restic if not already done
  block:
    - name: check status of restic repo "{{ target_location }}/{{ backup_name }}"
      ansible.builtin.expect:
        command: restic stats -r "{{ target_location }}/{{ backup_name }}"
        responses:
          password: "{{ backup_borg_encryption_key }}"
      become: true
      become_user: "{{ backup_systemd_user }}"
      timeout: 240
      environment:
        AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
        AWS_DEFAULT_REGION: "{{ AWS_DEFAULT_REGION }}"
        AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
        AZURE_ACCOUNT_KEY: "{{ AZURE_ACCOUNT_KEY }}"
        AZURE_ACCOUNT_NAME: "{{ AZURE_ACCOUNT_NAME }}"
        B2_ACCOUNT_ID: "{{ B2_ACCOUNT_ID }}"
        B2_ACCOUNT_KEY: "{{ B2_ACCOUNT_KEY }}"
        GOOGLE_APPLICATION_CREDENTIALS: "{{ GOOGLE_APPLICATION_CREDENTIALS }}"
        GOOGLE_PROJECT_ID: "{{ GOOGLE_PROJECT_ID }}"
        OS_APPLICATION_CREDENTIAL_ID: "{{ OS_APPLICATION_CREDENTIAL_ID }}"
        OS_APPLICATION_CREDENTIAL_NAME: "{{ OS_APPLICATION_CREDENTIAL_NAME }}"
        OS_APPLICATION_CREDENTIAL_SECRETS: "{{ OS_APPLICATION_CREDENTIAL_SECRETS }}"
        OS_AUTH_TOKEN: "{{ OS_AUTH_TOKEN }}"
        OS_AUTH_URL: "{{ OS_AUTH_URL }}"
        OS_PASSWORD: "{{ OS_PASSWORD }}"
        OS_PROJECT_DOMAIN_ID: "{{ OS_PROJECT_DOMAIN_ID }}"
        OS_PROJECT_DOMAIN_NAME: "{{ OS_PROJECT_DOMAIN_NAME }}"
        OS_PROJECT_NAME: "{{ OS_PROJECT_NAME }}"
        OS_REGION_NAME: "{{ OS_REGION_NAME }}"
        OS_TENANT_ID: "{{ OS_TENANT_ID }}"
        OS_TENANT_NAME: "{{ OS_TENANT_NAME }}"
        OS_TRUST_ID: "{{ OS_TRUST_ID }}"
        OS_USER_DOMAIN_ID: "{{ OS_USER_DOMAIN_ID }}"
        OS_USER_DOMAIN_NAME: "{{ OS_USER_DOMAIN_NAME }}"
        OS_USER_ID: "{{ OS_USER_ID }}"
        OS_USERNAME: "{{ OS_USERNAME }}"
        SOS_STORAGE_URL: "{{ SOS_STORAGE_URL }}"
        ST_AUTH: "{{ ST_AUTH }}"
        ST_KEY: "{{ ST_KEY }}"
        ST_USER: "{{ ST_USER }}"
  rescue:
    - name: initialize restic repo "{{ target_location }}/{{ backup_name }}"
      ansible.builtin.expect:
        command: restic init -r "{{ target_location }}/{{ backup_name }}"
        responses:
          password:
            - "{{ backup_borg_encryption_key }}"
            - "{{ backup_borg_encryption_key }}"
            - "n"
            - ""
      environment:
        AWS_ACCESS_KEY_ID: "{{ AWS_ACCESS_KEY_ID }}"
        AWS_DEFAULT_REGION: "{{ AWS_DEFAULT_REGION }}"
        AWS_SECRET_ACCESS_KEY: "{{ AWS_SECRET_ACCESS_KEY }}"
        AZURE_ACCOUNT_KEY: "{{ AZURE_ACCOUNT_KEY }}"
        AZURE_ACCOUNT_NAME: "{{ AZURE_ACCOUNT_NAME }}"
        B2_ACCOUNT_ID: "{{ B2_ACCOUNT_ID }}"
        B2_ACCOUNT_KEY: "{{ B2_ACCOUNT_KEY }}"
        GOOGLE_APPLICATION_CREDENTIALS: "{{ GOOGLE_APPLICATION_CREDENTIALS }}"
        GOOGLE_PROJECT_ID: "{{ GOOGLE_PROJECT_ID }}"
        OS_APPLICATION_CREDENTIAL_ID: "{{ OS_APPLICATION_CREDENTIAL_ID }}"
        OS_APPLICATION_CREDENTIAL_NAME: "{{ OS_APPLICATION_CREDENTIAL_NAME }}"
        OS_APPLICATION_CREDENTIAL_SECRETS: "{{ OS_APPLICATION_CREDENTIAL_SECRETS }}"
        OS_AUTH_TOKEN: "{{ OS_AUTH_TOKEN }}"
        OS_AUTH_URL: "{{ OS_AUTH_URL }}"
        OS_PASSWORD: "{{ OS_PASSWORD }}"
        OS_PROJECT_DOMAIN_ID: "{{ OS_PROJECT_DOMAIN_ID }}"
        OS_PROJECT_DOMAIN_NAME: "{{ OS_PROJECT_DOMAIN_NAME }}"
        OS_PROJECT_NAME: "{{ OS_PROJECT_NAME }}"
        OS_REGION_NAME: "{{ OS_REGION_NAME }}"
        OS_TENANT_ID: "{{ OS_TENANT_ID }}"
        OS_TENANT_NAME: "{{ OS_TENANT_NAME }}"
        OS_TRUST_ID: "{{ OS_TRUST_ID }}"
        OS_USER_DOMAIN_ID: "{{ OS_USER_DOMAIN_ID }}"
        OS_USER_DOMAIN_NAME: "{{ OS_USER_DOMAIN_NAME }}"
        OS_USER_ID: "{{ OS_USER_ID }}"
        OS_USERNAME: "{{ OS_USERNAME }}"
        SOS_STORAGE_URL: "{{ SOS_STORAGE_URL }}"
        ST_AUTH: "{{ ST_AUTH }}"
        ST_KEY: "{{ ST_KEY }}"
        ST_USER: "{{ ST_USER }}"
