---
- name: Initialize borg if not already done
  block:
    - name: Check status of borg repo
      ansible.builtin.expect:
        command: borg info {{ target_location }}/{{ backup_name }}
        responses:
          passphrase: "{{ backup_borg_encryption_key }}"
  rescue:
    - name: Initialize borg
      ansible.builtin.expect:
        command: borg init --encryption={{ backup_borg_encryption_method }} {{ target_location }}/{{ backup_name }}
        responses:
          passphrase:
            - "{{ backup_borg_encryption_key }}"
            - "{{ backup_borg_encryption_key }}"
            - "n"
            - ""
