---
- name: Initialize restic if not already done
  block:
    - name: Check status of restic repo "{{ target_location }}/{{ backup_name }}"
      ansible.builtin.expect:
        command: restic stats -r "{{ target_location }}/{{ backup_name }}"
        responses:
          password: "{{ backup_borg_encryption_key }}"
      become: true
      become_user: "{{ backup_systemd_user }}"
      timeout: 240
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_DEFAULT_REGION: "{{ aws_default_region }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AZURE_ACCOUNT_KEY: "{{ azure_account_key }}"
        AZURE_ACCOUNT_NAME: "{{ azure_account_name }}"
        B2_ACCOUNT_ID: "{{ b2_account_id }}"
        B2_ACCOUNT_KEY: "{{ b2_account_key }}"
        GOOGLE_APPLICATION_CREDENTIALS: "{{ google_application_credentials }}"
        GOOGLE_PROJECT_ID: "{{ google_project_id }}"
        OS_APPLICATION_CREDENTIAL_ID: "{{ os_application_credential_id }}"
        OS_APPLICATION_CREDENTIAL_NAME: "{{ os_application_credential_name }}"
        OS_APPLICATION_CREDENTIAL_SECRET: "{{ os_application_credential_secret }}"
        OS_AUTH_TOKEN: "{{ os_auth_token }}"
        OS_AUTH_URL: "{{ os_auth_url }}"
        OS_PASSWORD: "{{ os_password }}"
        OS_PROJECT_DOMAIN_ID: "{{ os_project_domain_id }}"
        OS_PROJECT_DOMAIN_NAME: "{{ os_project_domain_name }}"
        OS_PROJECT_NAME: "{{ os_project_name }}"
        OS_REGION_NAME: "{{ os_region_name }}"
        OS_TENANT_ID: "{{ os_tenant_id }}"
        OS_TENANT_NAME: "{{ os_tenant_name }}"
        OS_TRUST_ID: "{{ os_trust_id }}"
        OS_USER_DOMAIN_ID: "{{ os_user_domain_id }}"
        OS_USER_DOMAIN_NAME: "{{ os_user_domain_name }}"
        OS_USER_ID: "{{ os_user_id }}"
        OS_USERNAME: "{{ os_username }}"
        OS_STORAGE_URL: "{{ os_storage_url }}"
        ST_AUTH: "{{ st_auth }}"
        ST_KEY: "{{ st_key }}"
        ST_USER: "{{ st_user }}"
  rescue:
    - name: Initialize restic repo "{{ target_location }}/{{ backup_name }}"
      ansible.builtin.expect:
        command: restic init -r "{{ target_location }}/{{ backup_name }}"
        responses:
          password:
            - "{{ backup_borg_encryption_key }}"
            - "{{ backup_borg_encryption_key }}"
            - "n"
            - ""
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_DEFAULT_REGION: "{{ aws_default_region }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
        AZURE_ACCOUNT_KEY: "{{ azure_account_key }}"
        AZURE_ACCOUNT_NAME: "{{ azure_account_name }}"
        B2_ACCOUNT_ID: "{{ b2_account_id }}"
        B2_ACCOUNT_KEY: "{{ b2_account_key }}"
        GOOGLE_APPLICATION_CREDENTIALS: "{{ google_application_credentials }}"
        GOOGLE_PROJECT_ID: "{{ google_project_id }}"
        OS_APPLICATION_CREDENTIAL_ID: "{{ os_application_credential_id }}"
        OS_APPLICATION_CREDENTIAL_NAME: "{{ os_application_credential_name }}"
        OS_APPLICATION_CREDENTIAL_SECRET: "{{ os_application_credential_secret }}"
        OS_AUTH_TOKEN: "{{ os_auth_token }}"
        OS_AUTH_URL: "{{ os_auth_url }}"
        OS_PASSWORD: "{{ os_password }}"
        OS_PROJECT_DOMAIN_ID: "{{ os_project_domain_id }}"
        OS_PROJECT_DOMAIN_NAME: "{{ os_project_domain_name }}"
        OS_PROJECT_NAME: "{{ os_project_name }}"
        OS_REGION_NAME: "{{ os_region_name }}"
        OS_TENANT_ID: "{{ os_tenant_id }}"
        OS_TENANT_NAME: "{{ os_tenant_name }}"
        OS_TRUST_ID: "{{ os_trust_id }}"
        OS_USER_DOMAIN_ID: "{{ os_user_domain_id }}"
        OS_USER_DOMAIN_NAME: "{{ os_user_domain_name }}"
        OS_USER_ID: "{{ os_user_id }}"
        OS_USERNAME: "{{ os_username }}"
        OS_STORAGE_URL: "{{ os_storage_url }}"
        ST_AUTH: "{{ st_auth }}"
        ST_KEY: "{{ st_key }}"
        ST_USER: "{{ st_user }}"
