---
- name: Set `target_location` to local directory
  ansible.builtin.set_fact:
    target_location: "{{ backup_target_dir }}"
  when: backup_restic_repo is not defined
  tags:
    - backup
- name: Set `target_location` to remote repo
  ansible.builtin.set_fact:
    target_location: "{{ backup_restic_repo }}:{{ backup_target_dir }}"
  when: backup_restic_repo is defined
  tags:
    - backup
- name: Set service name for remote restic
  ansible.builtin.set_fact:
    service_name: "{{ backup_name }}-{{ backup_restic_repo | replace(':', '-') | replace('/', '') }}"
  when: backup_restic_repo is defined
  tags:
    - backup
- name: Set service name for local restic
  ansible.builtin.set_fact:
    service_name: "{{ backup_name }}-local"
  when: backup_restic_repo is not defined
  tags:
    - backup
- name: Install restic
  ansible.builtin.import_tasks: install-restic.yml
  tags:
    - backup
- name: Delete restic repository
  ansible.builtin.import_tasks: delete-restic-repo.yml
  when: backup_delete
  tags:
    - backup
- name: Delete systemd service
  ansible.builtin.import_tasks: delete-service.yml
  when: backup_delete
  tags:
    - backup
- name: Install restic systemd service
  ansible.builtin.import_tasks: install-service.yml
  become: true
  tags:
    - backup
- name: Initialize restic repository
  ansible.builtin.import_tasks: initialize-restic-repo.yml
  when: backup_create
  tags:
    - backup
