name: main and pr builds

on:
  push:
    branches:
    - master
    - main
  pull_request:
    branches:
    - master
    - main
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: papanito/github-actions-workflows/.github/workflows/ansible-roles-build.yml@main
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}